language: ruby
rvm:
  - 2.7.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: 
  - bundler # caching bundler gem packages will speed up build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
install: 
- gem install pygments.rb
- gem install jekyll bundler jekyll-feed jekyll-sitemap minima html-proofer
before_script:
- chmod +x ./script/cibuild.sh # or do this locally and commit
script:
- ./script/cibuild.sh
deploy:
- provider: pages
  local-dir: ./_site
  skip_cleanup: true
  fqdn: strapdata.com
  deployment_file: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  on:
    branch: master
