title: Amélie Royer Sophrologue
email: contact@amelie-sophrologue.com
description: >-
  Amélie Royer Sophrologue, Sophrologie, Neurofeedback, Hypnose.
baseurl: ''
url: 'https://amelie-sophrologue.com'
twitter_username: ameliesophrologue
github_username: amelieroyer
theme: minima
plugins:
  - jekyll-sitemap
exclude:
  - vendor
